name: "Test sections"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: Run tests
        run: make tests

      - name: Run benchmarks
        run: make benchmarks
